name: build KSU kernel - OPPO Reno6

on:
  workflow_dispatch:
jobs:

  build-kernel:

    runs-on: fkrystal-1

    steps:
      - name: Pull toolchain

        run: |

          cd $HOME
          rm -rf aarch64-linux-android-4.9
          rm -rf arm-linux-androideabi-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9

      - name: Pull clang

        run: |
          
          cd $HOME
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=2

      - name: Pull kernel source

        run: |

          aria2c https://github.com/dabao1955/android_kernel_OPPO_PEQM00/archive/refs/heads/4.19-ksu-dev.zip

          unzip -q android_kernel_OPPO_PEQM00-4.19-ksu-dev.zip 

          mv android_kernel_OPPO_PEQM00-4.19-ksu-dev kernel-4.19 -v

      - name: Pull kernel vendor source

        run: |

          git clone https://github.com/oppo-source/android_kernel_modules_oppo_mtk_4.19/

          sleep 1s

          cp android_kernel_modules_oppo_mtk_4.19/vendor ../vnd -R

          cp android_kernel_modules_oppo_mtk_4.19/vendor/oplus/kernel_4.19/audio/ kernel-4.19/sound/soc/codecs -R -v

      - name: Sync KernelSU

        run: |

          export KBUILD_BUILD_USER="dabao1955"

          cd /home/runner/work/android_kernel_OPPO_PEQM00/android_kernel_OPPO_PEQM00/kernel-4.19

          bash setup.sh
      - name: Setup ccache

        uses: hendrikmuhs/ccache-action@main

        with: 

         max-size: 4G
         key: r6-419

      - name: Build KernelSU kernel - OPPO Reno 6

        run: |

          cd /home/runner/work/android_kernel_OPPO_PEQM00/android_kernel_OPPO_PEQM00/kernel-4.19
          
          test -f build_kernel.sh && rm build_kernel.sh && wget https://raw.githubusercontent.com/dabao1955/android_kernel_OPPO_PEQM00/README/build_kernel.sh

          bash build_kernel.sh

      - name: Upload kernel to artifact

        uses: actions/upload-artifact@v4

        with:

          name: kernel-6877-4.19-ksu

          path: kernel-4.19/out/arch/arm64/boot/*

